services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=api
      - DB_USER=oleksandr
      - DB_PASS=passwordparaaapi
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=oleksandr
      - POSTGRES_PASSWORD=passwordparaaapi
